# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/fpga_pinout.xdc

# Block Designs: bd/cpu_system/cpu_system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_system || ORIG_REF_NAME==cpu_system} -quiet] -quiet

# IP: bd/cpu_system/ip/cpu_system_microblaze_0_0/cpu_system_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_system_microblaze_0_0 || ORIG_REF_NAME==cpu_system_microblaze_0_0} -quiet] -quiet

# IP: bd/cpu_system/ip/cpu_system_mig_7series_0_0/cpu_system_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_system_mig_7series_0_0 || ORIG_REF_NAME==cpu_system_mig_7series_0_0} -quiet] -quiet

# IP: bd/cpu_system/ip/cpu_system_axi_uartlite_0_0/cpu_system_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_system_axi_uartlite_0_0 || ORIG_REF_NAME==cpu_system_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/cpu_system/ip/cpu_system_mdm_1_0/cpu_system_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_system_mdm_1_0 || ORIG_REF_NAME==cpu_system_mdm_1_0} -quiet] -quiet

# IP: bd/cpu_system/ip/cpu_system_rst_mig_7series_0_100M_0/cpu_system_rst_mig_7series_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_system_rst_mig_7series_0_100M_0 || ORIG_REF_NAME==cpu_system_rst_mig_7series_0_100M_0} -quiet] -quiet

# IP: bd/cpu_system/ip/cpu_system_axi_smc_0/cpu_system_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_system_axi_smc_0 || ORIG_REF_NAME==cpu_system_axi_smc_0} -quiet] -quiet

# IP: bd/cpu_system/ip/cpu_system_microblaze_0_axi_periph_0/cpu_system_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_system_microblaze_0_axi_periph_0 || ORIG_REF_NAME==cpu_system_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/cpu_system/ip/cpu_system_axi_dma_0_0/cpu_system_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_system_axi_dma_0_0 || ORIG_REF_NAME==cpu_system_axi_dma_0_0} -quiet] -quiet

# IP: bd/cpu_system/ip/cpu_system_system_ila_0_0/cpu_system_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_system_system_ila_0_0 || ORIG_REF_NAME==cpu_system_system_ila_0_0} -quiet] -quiet

# IP: bd/cpu_system/ip/cpu_system_xbar_0/cpu_system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_system_xbar_0 || ORIG_REF_NAME==cpu_system_xbar_0} -quiet] -quiet

# IP: bd/cpu_system/ip/cpu_system_dlmb_v10_0/cpu_system_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_system_dlmb_v10_0 || ORIG_REF_NAME==cpu_system_dlmb_v10_0} -quiet] -quiet

# IP: bd/cpu_system/ip/cpu_system_ilmb_v10_0/cpu_system_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_system_ilmb_v10_0 || ORIG_REF_NAME==cpu_system_ilmb_v10_0} -quiet] -quiet

# IP: bd/cpu_system/ip/cpu_system_dlmb_bram_if_cntlr_0/cpu_system_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_system_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==cpu_system_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/cpu_system/ip/cpu_system_ilmb_bram_if_cntlr_0/cpu_system_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_system_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==cpu_system_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/cpu_system/ip/cpu_system_lmb_bram_0/cpu_system_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_system_lmb_bram_0 || ORIG_REF_NAME==cpu_system_lmb_bram_0} -quiet] -quiet

# IP: bd/cpu_system/ip/cpu_system_fifo_generator_0_0/cpu_system_fifo_generator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_system_fifo_generator_0_0 || ORIG_REF_NAME==cpu_system_fifo_generator_0_0} -quiet] -quiet

# XDC: bd/cpu_system/cpu_system_ooc.xdc
