# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/cpu_system_axi_smc_0.xci
# IP: The module: 'cpu_system_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/bd_e077.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_10/bd_e077_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_19/bd_e077_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_25/bd_e077_s02a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_31/bd_e077_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_37/bd_e077_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_32/bd_e077_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_33/bd_e077_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_34/bd_e077_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_35/bd_e077_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_36/bd_e077_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_26/bd_e077_sarn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_27/bd_e077_srn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_28/bd_e077_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_29/bd_e077_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_30/bd_e077_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_22/bd_e077_s02mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_23/bd_e077_s02tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_24/bd_e077_s02sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_20/bd_e077_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_21/bd_e077_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_16/bd_e077_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_17/bd_e077_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_18/bd_e077_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_11/bd_e077_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_12/bd_e077_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_13/bd_e077_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_14/bd_e077_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_15/bd_e077_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_7/bd_e077_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_8/bd_e077_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_9/bd_e077_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_2/bd_e077_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_3/bd_e077_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_4/bd_e077_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_5/bd_e077_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_6/bd_e077_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_0/bd_e077_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_1/bd_e077_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_10/bd_e077_s00a2s_0_ooc.xdc

# XDC: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_19/bd_e077_s01a2s_0_ooc.xdc

# XDC: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_25/bd_e077_s02a2s_0_ooc.xdc

# XDC: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_31/bd_e077_m00s2a_0_ooc.xdc

# XDC: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_32/bd_e077_m00arn_0_ooc.xdc

# XDC: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_33/bd_e077_m00rn_0_ooc.xdc

# XDC: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_34/bd_e077_m00awn_0_ooc.xdc

# XDC: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_35/bd_e077_m00wn_0_ooc.xdc

# XDC: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_36/bd_e077_m00bn_0_ooc.xdc

# XDC: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_26/bd_e077_sarn_2_ooc.xdc

# XDC: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_27/bd_e077_srn_2_ooc.xdc

# XDC: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_28/bd_e077_sawn_1_ooc.xdc

# XDC: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_29/bd_e077_swn_1_ooc.xdc

# XDC: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_30/bd_e077_sbn_1_ooc.xdc

# XDC: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_20/bd_e077_sarn_1_ooc.xdc

# XDC: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_21/bd_e077_srn_1_ooc.xdc

# XDC: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_11/bd_e077_sarn_0_ooc.xdc

# XDC: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_12/bd_e077_srn_0_ooc.xdc

# XDC: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_13/bd_e077_sawn_0_ooc.xdc

# XDC: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_14/bd_e077_swn_0_ooc.xdc

# XDC: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_15/bd_e077_sbn_0_ooc.xdc

# XDC: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_2/bd_e077_arsw_0_ooc.xdc

# XDC: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_3/bd_e077_rsw_0_ooc.xdc

# XDC: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_4/bd_e077_awsw_0_ooc.xdc

# XDC: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_5/bd_e077_wsw_0_ooc.xdc

# XDC: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_6/bd_e077_bsw_0_ooc.xdc

# XDC: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_1/bd_e077_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_1/bd_e077_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_system_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/cpu_system_axi_smc_0.xci
# IP: The module: 'cpu_system_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/bd_e077.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_10/bd_e077_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_19/bd_e077_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_25/bd_e077_s02a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_31/bd_e077_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_37/bd_e077_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_32/bd_e077_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_33/bd_e077_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_34/bd_e077_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_35/bd_e077_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_36/bd_e077_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_26/bd_e077_sarn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_27/bd_e077_srn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_28/bd_e077_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_29/bd_e077_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_30/bd_e077_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_22/bd_e077_s02mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_23/bd_e077_s02tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_24/bd_e077_s02sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_20/bd_e077_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_21/bd_e077_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_16/bd_e077_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_17/bd_e077_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_18/bd_e077_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_11/bd_e077_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_12/bd_e077_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_13/bd_e077_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_14/bd_e077_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_15/bd_e077_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_7/bd_e077_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_8/bd_e077_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_9/bd_e077_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_2/bd_e077_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_3/bd_e077_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_4/bd_e077_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_5/bd_e077_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_6/bd_e077_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_0/bd_e077_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_1/bd_e077_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_10/bd_e077_s00a2s_0_ooc.xdc

# XDC: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_19/bd_e077_s01a2s_0_ooc.xdc

# XDC: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_25/bd_e077_s02a2s_0_ooc.xdc

# XDC: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_31/bd_e077_m00s2a_0_ooc.xdc

# XDC: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_32/bd_e077_m00arn_0_ooc.xdc

# XDC: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_33/bd_e077_m00rn_0_ooc.xdc

# XDC: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_34/bd_e077_m00awn_0_ooc.xdc

# XDC: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_35/bd_e077_m00wn_0_ooc.xdc

# XDC: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_36/bd_e077_m00bn_0_ooc.xdc

# XDC: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_26/bd_e077_sarn_2_ooc.xdc

# XDC: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_27/bd_e077_srn_2_ooc.xdc

# XDC: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_28/bd_e077_sawn_1_ooc.xdc

# XDC: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_29/bd_e077_swn_1_ooc.xdc

# XDC: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_30/bd_e077_sbn_1_ooc.xdc

# XDC: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_20/bd_e077_sarn_1_ooc.xdc

# XDC: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_21/bd_e077_srn_1_ooc.xdc

# XDC: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_11/bd_e077_sarn_0_ooc.xdc

# XDC: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_12/bd_e077_srn_0_ooc.xdc

# XDC: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_13/bd_e077_sawn_0_ooc.xdc

# XDC: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_14/bd_e077_swn_0_ooc.xdc

# XDC: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_15/bd_e077_sbn_0_ooc.xdc

# XDC: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_2/bd_e077_arsw_0_ooc.xdc

# XDC: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_3/bd_e077_rsw_0_ooc.xdc

# XDC: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_4/bd_e077_awsw_0_ooc.xdc

# XDC: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_5/bd_e077_wsw_0_ooc.xdc

# XDC: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_6/bd_e077_bsw_0_ooc.xdc

# XDC: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_1/bd_e077_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/bd_0/ip/ip_1/bd_e077_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: f:/Egyetem/mikrorendszerek/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_system_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
