# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/D_Strabi/D_Dokumentumai/BME/MikrorendszerekTevezese/HF/K-gy-j-t-k/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_xbar_0/cpu_system_xbar_0.xci
# IP: The module: 'cpu_system_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/D_Strabi/D_Dokumentumai/BME/MikrorendszerekTevezese/HF/K-gy-j-t-k/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_xbar_0/cpu_system_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_system_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/D_Strabi/D_Dokumentumai/BME/MikrorendszerekTevezese/HF/K-gy-j-t-k/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_xbar_0/cpu_system_xbar_0.xci
# IP: The module: 'cpu_system_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/D_Strabi/D_Dokumentumai/BME/MikrorendszerekTevezese/HF/K-gy-j-t-k/ddr3_dma/ddr3_dma.srcs/sources_1/bd/cpu_system/ip/cpu_system_xbar_0/cpu_system_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_system_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
